class PayslipPdfGenerator
  require 'prawn'
  require 'prawn/table'

  def initialize(payslip)
    @payslip = payslip
    @employee = payslip.employee
    @pdf = Prawn::Document.new
  end

  def generate
    add_header
    add_company_info
    add_employee_info
    add_payslip_details
    add_salary_breakdown
    add_footer
    @pdf.render
  end

  private

  def add_header
    @pdf.text "PAYSLIP", size: 30, style: :bold, align: :center, color: "15803D"
    @pdf.move_down 20
  end

  def add_company_info
    @pdf.text "RailsLips", size: 18, style: :bold
    @pdf.text "Payslip Management System", size: 10
    @pdf.move_down 5
    @pdf.stroke_horizontal_rule
    @pdf.move_down 20
  end

  def add_employee_info
    @pdf.text "Employee Information", size: 14, style: :bold, color: "15803D"
    @pdf.move_down 10

    employee_data = [
      ["Employee Name:", "#{@employee.first_name} #{@employee.last_name}"],
      ["Email:", @employee.user.email],
      ["Department:", @employee.department || "N/A"]
    ]

    @pdf.table(employee_data, width: @pdf.bounds.width, cell_style: { borders: [] }) do
      cells.padding = 5
      column(0).font_style = :bold
      column(0).width = 150
    end

    @pdf.move_down 20
  end

  def add_payslip_details
    @pdf.text "Payslip Details", size: 14, style: :bold, color: "15803D"
    @pdf.move_down 10

    details_data = [
      ["Payslip Number:", @payslip.unique_number],
      ["Pay Period:", "#{@payslip.start_period.strftime('%b %d, %Y')} - #{@payslip.end_period.strftime('%b %d, %Y')}"],
      ["Pay Date:", @payslip.pay_date.strftime('%b %d, %Y')],
      ["Issue Date:", @payslip.date.strftime('%b %d, %Y')],
      ["Generated By:", @payslip.generated_by.email]
    ]

    @pdf.table(details_data, width: @pdf.bounds.width, cell_style: { borders: [] }) do
      cells.padding = 5
      column(0).font_style = :bold
      column(0).width = 150
    end

    @pdf.move_down 20
  end

  def add_salary_breakdown
    @pdf.text "Salary Breakdown", size: 14, style: :bold, color: "15803D"
    @pdf.move_down 10

    salary_data = [
      [{ content: "Description", background_color: "D1FAE5" }, 
       { content: "Amount", background_color: "D1FAE5" }],
      ["Gross Salary", "€#{format_currency(@payslip.salary)}"]
    ]

    @pdf.table(salary_data, width: @pdf.bounds.width) do
      cells.padding = 10
      row(0).font_style = :bold
      row(0).align = :center
      column(1).align = :right
    end

    @pdf.move_down 10

    # Total
    @pdf.table([
      [{ content: "Net Salary", background_color: "15803D", text_color: "FFFFFF" },
       { content: "€#{format_currency(@payslip.salary)}", background_color: "15803D", text_color: "FFFFFF" }]
    ], width: @pdf.bounds.width) do
      cells.padding = 12
      cells.font_style = :bold
      cells.size = 14
      column(1).align = :right
    end

    @pdf.move_down 20
  end

  def add_footer
    if @payslip.notes.present?
      @pdf.text "Notes:", size: 12, style: :bold
      @pdf.move_down 5
      @pdf.text @payslip.notes, size: 10
      @pdf.move_down 20
    end

    @pdf.move_down 30
    @pdf.stroke_horizontal_rule
    @pdf.move_down 10
    
    @pdf.text "This is a computer-generated document. No signature is required.", 
              size: 8, 
              align: :center, 
              style: :italic,
              color: "666666"
    
    @pdf.text "Generated on #{Time.current.strftime('%B %d, %Y at %I:%M %p')}", 
              size: 8, 
              align: :center,
              color: "666666"
  end

  def format_currency(amount)
    sprintf('%.2f', amount)
  end
end

