services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: bookingexperts
      POSTGRES_PASSWORD: bookingexperts_password
      POSTGRES_DB: bookingexperts_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookingexperts -d bookingexperts_development"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: bookingexperts
      DATABASE_PASSWORD: bookingexperts_password
      DATABASE_NAME: bookingexperts_development
      PGHOST: db
      PGPORT: 5432
      PGUSER: bookingexperts
      PGPASSWORD: bookingexperts_password
      PGDATABASE: bookingexperts_development

volumes:
  postgres_data:
  bundle_cache:

