request_statuses:
  pending:
    label: 'Pending'
    icon: 'clock'
    badge_class: 'bg-yellow-100 text-yellow-800 border border-yellow-200'
    icon_bg: 'bg-yellow-50'
    icon_color: 'text-yellow-600'
  
  approved:
    label: 'Approved'
    icon: 'check-circle'
    badge_class: 'bg-green-100 text-green-800 border border-green-200'
    icon_bg: 'bg-green-50'
    icon_color: 'text-green-600'
  
  rejected:
    label: 'Rejected'
    icon: 'x-circle'
    badge_class: 'bg-red-100 text-red-800 border border-red-200'
    icon_bg: 'bg-red-50'
    icon_color: 'text-red-600'

leave_types:
  vacation:
    label: 'Vacation'
    badge_class: 'bg-blue-100 text-blue-800 border border-blue-200'
  
  sick_leave:
    label: 'Sick Leave'
    badge_class: 'bg-purple-100 text-purple-800 border border-purple-200'
  
  personal_leave:
    label: 'Personal Leave'
    badge_class: 'bg-indigo-100 text-indigo-800 border border-indigo-200'
  
  unpaid_leave:
    label: 'Unpaid Leave'
    badge_class: 'bg-gray-100 text-gray-800 border border-gray-200'
  
  other:
    label: 'Other'
    badge_class: 'bg-gray-100 text-gray-800 border border-gray-200'

